### ISSUE TITLE
Loading hangs on Safari 15.3 on macOS Big Sur 11.6.3

### ISSUE THREAD

**Issue by enwinn** [leaningtech/webvm#19] opened 2022-02-03 18:02 UTC
With Content Blocker active for the site the entire tab froze and was unresponsive. Turning off content blocker seemed to allow the tab to unfreeze but still failed to load. Got most of the way but never generated your default error message.

Subsequent launch in a new tab just came up blank. Hitting refresh showed a progress bar along the bottom of the address bar but page still remained blank until running a force reload but then it just gets back to a block cursor under the vim examples/c/helloworld.c line and never recovers.

Seems to work OK with Edge Dev 99.0.1150.2 (Official build) Dev (x86_64) on macOS 11.6.3 albeit a bit slow to finish initializing.
Similar hang on Firefox 96.0.3, and I had to turn off enhanced tracking to get to about the same point I got to in Safari.
Seems to work OK on Chrome Version 98.0.4758.80 on macOS 11.6.3. Init was faster than Edge Dev.

![image](https://user-images.githubusercontent.com/11488937/152385364-9488815d-8491-4dd3-adde-8d76937d2c25.png)

**Comment by sere** [comment] 2022-02-08 10:47
I cannot reproduce this behavior on Safari 15.2 / 15.3 / 15.4, nor on IPhone.

I tested with both content blocker active (Safari 15.2 on macOS Monterey) and with content blocker disabled. Firefox also works for me with enhanced tracking and "strict" privacy settings.

Can you try to clear the cache and IndexedDB and try again?

**Comment by alexp-sssup** [comment] 2022-06-23 08:25
Closing this bug due to lack of precise information. Most likely a side-effect of content blocking.

**Closed by alexp-sssup** 2022-06-23 08:25 UTC
