### ISSUE TITLE
how to deploy webvm via xampp?

### ISSUE THREAD

**Issue by YinYongHongYork** [leaningtech/webvm#114] opened 2024-08-25 05:27 UTC
1. clone webvm under htdocs folder
2. follow the guide of "Local deployment"
3. place  "debian_mini_20230519_5022088024.ext2"  under "htdocs\webvm\"
4. launch webvm in edge brower.
5. pending for long time
![2024-08-25 13-27-50](https://github.com/user-attachments/assets/2c98d0f1-486a-4250-8270-cf38f44c9705)

**Comment by saarikoski-jules** [comment] 2024-08-26 06:42
I'll need some extra information to be able to help. Could you show me what's going on in the browser devtools network tab, and if there are any messages in the console? Are you using the included nginx configuration?

**Comment by YinYongHongYork** [comment] 2024-08-26 08:05
![2024-08-26 15-56-23](https://github.com/user-attachments/assets/b17ee171-6350-4a48-b313-860b9daf39b5)

**Comment by YinYongHongYork** [comment] 2024-08-26 08:06
thank u for your reply.

the attached info:

![2024-08-26 15-56-23](https://github.com/user-attachments/assets/9b47f549-9ffb-45d8-b635-7da0b05edf58)

**Comment by saarikoski-jules** [comment] 2024-08-26 08:12
It looks like you forgot to comment out the original definition of cmd in index.html, on line 269.

**Comment by saarikoski-jules** [comment] 2024-08-27 06:51
Since there's no more activity on this issue, I'm going to assume the issue is resolved and will close this.

**Closed by saarikoski-jules** 2024-08-27 06:51 UTC
