### ISSUE TITLE
Fault while using numpy

### ISSUE THREAD

**Issue by Masterchef365** [leaningtech/webvm#79] opened 2023-06-20 06:31 UTC
Reproducing the fault is as easy as visiting <https://webvm.io/> and:
```py
$ python3
>>> import numpy as np
>>> np.linspace(0., 1., 3)
```
The JS console reports:
```
TODO: FAULT af8ef5e2 [cxcore-no-return-call.js:1:63609](https://cheerpxdemos.leaningtech.com/publicdeploy/20230609_107/cxcore-no-return-call.js)
CODE 0 2e 0
```
This only seems to happen with `np.linspace(..., >3)`

FYI I'm using FireFox 114.0.1, same thing happens on 116.0a1

**Comment by alexp-sssup** [comment] 2023-06-20 08:13
The crash was caused by a non-implemented instruction, and it is now fixed.

Please make sure to clear the browser cache before trying again, to make sure the new build is used.

**Closed by alexp-sssup** 2023-06-20 08:13 UTC

**Comment by Masterchef365** [comment] 2023-06-20 09:09
Nice work! Tested it from my phone :heart:
