### ISSUE TITLE
which git fails due to shebang

### ISSUE THREAD

**Issue by bk2204** [leaningtech/webvm#13] opened 2022-02-02 20:36 UTC
Running `which git` fails:

```
user@:~$ which git
bash: /usr/bin/which: /bin/sh: bad interpreter: Invalid argument
```

This appears to be because `#! /bin/sh` (in `which`) is not recognized as a valid shebang.  While it is very common to omit a space after the `#!`, spaces have been permitted since Unix Version 8, and Linux allows them.

**Comment by sere** [comment] 2022-02-03 14:49
Hello, thanks for the report. We indeed handle this case incorrectly. We added this bug to our bucket list

**Comment by Alex-A137** [comment] 2022-04-23 02:08
how about fixing it now

**Comment by alexp-sssup** [comment] 2024-03-07 15:39
The problem is now fixed

**Closed by alexp-sssup** 2024-03-07 15:39 UTC
Labels: Type: bug, Priority: medium
