### ISSUE TITLE
apt-update: unexpected exit

### ISSUE THREAD

**Issue by lovasoa** [leaningtech/webvm#2] opened 2022-02-01 21:05 UTC
Running `apt update` results in the following error being thrown:

```
Unexpected exit @https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js line 1 > WebAssembly.instantiate:wasm-function[4076]:0x22f9b8
@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js line 1 > WebAssembly.instantiate:wasm-function[5696]:0x28a392
@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js line 1 > WebAssembly.instantiate:wasm-function[1299]:0x5260e
@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js line 1 > WebAssembly.instantiate:wasm-function[131]:0x747b
@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js line 1 > WebAssembly.instantiate:wasm-function[4190]:0x2402ba
ax6@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js:1:65688
ax5@https://cheerpxdemos.leaningtech.com/publicdeploy/20220131_700/cxcore.js:1:66104
```

![image](https://user-images.githubusercontent.com/552629/152050848-8cfd3ebf-1e9a-426f-a70b-92bbb1e5f8d7.png)

It would be awesome if we could install new software into webvm. The vm could try to detect http requests from socket syscalls, and translate them to fetch requests, or use something like https://github.com/benjamincburns/websockproxy

**Comment by carlopi** [comment] 2022-02-01 21:50
I do reproduce, thanks for opening this.

**Comment by sere** [comment] 2022-02-02 11:47
Thanks for reporting this, I've added the error to the queue.

Please note that for the moment WebVM has no network and sudo support, so it won't be possible to install programs anyway.

**Comment by sholtomaud** [comment] 2022-06-16 21:25
Without programs install (apt install) of curl or sudo there is no point to this WebVM ... "Web" means internet :) . It could be called just LocalVM or NoWebVM instead. :) 

I'm guessing the aspiration is parity with an actual VM so the suggestion here is to prioritise internet and install features.

**Comment by yuri91** [comment] 2022-10-07 10:03
apt does not crash anymore. We also have network support now, but note that apt will still not install packages.
For that we need actual root support (https://github.com/leaningtech/webvm/issues/8) and pty devices support.
I am still closing this issue since now the program does not crash but just regularly exits with an appropriate error.
Feel free to open an issue about supporting installing packages via apt.

**Closed by yuri91** 2022-10-07 10:03 UTC
Labels: Type: bug, Priority: high
