### ISSUE TITLE
no redirect

### ISSUE THREAD

**Issue by OMEGA6405** [leaningtech/webvm#66] opened 2023-05-18 17:27 UTC
whenever i click Connect via Tailscale it just says "Loading network code..." and then dose nothing

**Comment by OMEGA6405** [comment] 2023-05-18 17:27
![image](https://github.com/leaningtech/webvm/assets/98067930/9f699a79-0650-491f-a67e-1e5766f8b2ee)

**Comment by alexp-sssup** [comment] 2023-05-19 07:02
We cannot reproduce this problem, we have recently upgraded the networking mechanism, so please make sure of clearing your browser cached (or use Incognito mode).

If that does not help, please provide the following additional information:

* Any logging in the Developer Tools console from both the "Tailscale login" page and the main "WebVM" page
* What browser are you using

**Comment by OMEGA6405** [comment] 2023-05-19 12:41
> We cannot reproduce this problem, we have recently upgraded the networking mechanism, so please make sure of clearing your browser cached (or use Incognito mode).
> 
> If that does not help, please provide the following additional information:
> 
> * Any logging in the Developer Tools console from both the "Tailscale login" page and the main "WebVM" page
> * What browser are you using

can you add a manual redirect?

**Comment by OMEGA6405** [comment] 2023-05-19 12:57
yeah nothing

**Comment by OMEGA6405** [comment] 2023-05-19 13:43
> Can you also confirm if you see this message on the WebVM page after clicking of "Connect via Tailscale" ![image](https://user-images.githubusercontent.com/191061/239544387-4a1c6421-9f2a-49d6-8c37-4f36180e04a3.png)

yes i see that

**Comment by OMEGA6405** [comment] 2023-05-19 14:34
@alexp-sssup so is there any way to fix this?

**Comment by alexp-sssup** [comment] 2023-05-19 14:53
Can you provide a screenshot of the network tab from the main WebVM page when the loading is stuck?

**Comment by alexp-sssup** [comment] 2023-05-19 14:56
I was referring to the "network tab" of the developer tools

**Comment by OMEGA6405** [comment] 2023-05-19 14:59
cant rn i will send when i get on my pc

**Comment by alexp-sssup** [comment] 2023-05-30 10:37
Without further information we won't be able to debug this matter, and it's likely that it could have been caused by a temporary network failure. Closing for now.

**Closed by alexp-sssup** 2023-05-30 10:37 UTC
